#!/usr/bin/env python3
"""Assemble the standalone benchmark work/ntt/yosupo_bench_asm.cpp.

Pieces, copied verbatim:
  * SIMD v0 NTT and KACTL NTT from kactl_bench.cpp (repository root), the user's
    original benchmark; the SIMD part is wrapped in `namespace simd0`.
  * The qasm kernel region of work/ntt/yosupo_convolution_asm_shoup_io_sse.cpp (the
    source of Library Checker submission 406478). With all assembly switches off it is
    the 406403 kernel (qflip s_ns_olbp): same code paths, bit-identical outputs.
  * standalone_driver.inc (timing, checks, <1 KiB report on stderr).
usage: make_bench.py [--out PATH]
"""
import argparse
import hashlib
from pathlib import Path

here = Path(__file__).resolve().parent
root = here.parents[2]


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--out', default=str(root / 'work/ntt/yosupo_bench_asm.cpp'))
    args = ap.parse_args()
    kb_path = root / 'kactl_bench.cpp'
    sub_path = root / 'work/ntt/yosupo_convolution_asm_shoup_io_sse.cpp'
    kb, sub = kb_path.read_text(), sub_path.read_text()
    simd = kb[kb.index('using u32 = uint32_t;'):kb.index('// ============================================================================\n'
                                                          '// KACTL NTT for correctness testing')]
    kactl_start = kb.index('namespace KACTL {')
    kactl = kb[kactl_start:kb.index('\n// Helper to access v8i array', kactl_start)].rstrip() + '\n'
    kernel = sub[sub.index('// Exploration 009 kernel "qasm"'):sub.index('}  // namespace qasm') + len('}  // namespace qasm')]
    driver = (here / 'standalone_driver.inc').read_text()
    src = f'''// QPoly NTT speed comparison for Library Checker (judge.yosupo.jp) - standalone file.
// Generated by work/ntt/asm_explore/make_bench.py; submit as C++23 to any problem
// (e.g. convolution_mod). It ignores stdin, prints nothing to stdout (expect WA),
// and writes a speed table plus an acceleration chart to std::cerr; open a test
// case's row on the submission page to see "Stderr" (the judge keeps 1 KiB).
// Every test case reruns it (~3 s each on Zen 3). Exit status 1 (RE) = check failed.
// Sizes 2^10..2^22; set bench::TIME_LIMIT_S (default 5) to the problem's time limit.
// Implementations (cyclic convolution mod 998244353, n = 2^k):
//   kactl   KACTL NTT (kactl.github.io, CC0) as in kactl_bench.cpp
//   simd-v0 the original AVX2 Montgomery NTT from kactl_bench.cpp
//   406403  qflip s_ns_olbp kernel of submission 406403 (C++ Shoup)
//   406478  the same kernel with generated inline assembly (submission 406478)
// Sources: kactl_bench.cpp SHA256 {sha(kb_path)[:16]}..., {sub_path.relative_to(root)}
// SHA256 {sha(sub_path)[:16]}..., standalone_driver.inc SHA256 {sha(here / "standalone_driver.inc")[:16]}...
// -DQPOLY_BENCH_MAX_LOG=20 stops at 2^20 (faster).
#if defined(__GNUC__) && !defined(__clang__)
#pragma GCC optimize("O3,unroll-loops")
#endif
#pragma GCC target("avx2,bmi")
#include <immintrin.h>
#include <cpuid.h>
#include <algorithm>
#include <array>
#include <cassert>
#include <chrono>
#include <cstdarg>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <string>
#include <type_traits>
#include <vector>

// ============================================================================
// simd-v0: verbatim from kactl_bench.cpp
// ============================================================================
namespace simd0 {{
{simd}}}  // namespace simd0

// ============================================================================
// KACTL: verbatim from kactl_bench.cpp
// ============================================================================
{kactl}
// ============================================================================
// 406403 / 406478 kernel: verbatim kernel region of {sub_path.name}
// ============================================================================
{kernel}

{driver}'''
    Path(args.out).write_text(src)
    print(args.out, len(src), 'bytes, SHA256', hashlib.sha256(src.encode()).hexdigest())


if __name__ == '__main__':
    main()
