#!/usr/bin/env python3
"""Generate the single-file Library Checker convolution_mod_large submission.

Inlines the local includes of a program (default final_main.cpp; solve_main.cpp for the
experiment builds): io007.hpp (exploration-007 I/O, verbatim), large_core.hpp / large.hpp
(exploration-010 drivers) and ../asm_explore/kernels/qasm.hpp (exploration-009 kernel) with
only the selected generated assembly variants, extracted by asm_explore/make_yosupo_asm.py's
trimmed(). The program text is otherwise identical to the harness build, so the measured
code is the delivered code.

usage: make_submission.py [--source final_main.cpp | solve_main.cpp --mode 2]
                          [--probe] [--define NAME=VALUE ...] [--out PATH]
"""
import argparse
import hashlib
import importlib.util
import re
import sys
from pathlib import Path

sys.dont_write_bytecode = True   # importing asm_explore/make_yosupo_asm.py must not leave __pycache__

here = Path(__file__).resolve().parent
root = here.parents[2]
spec = importlib.util.spec_from_file_location('mya', here.parent / 'asm_explore/make_yosupo_asm.py')
mya = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mya)

# Exploration-009 selected configuration (qlarge::Sel): forward 11, h=4 forward 104,
# inverse 71, leaf 0 (C++ path unused with the fused bottom), fused bottom 23,
# identity-group loops 2, final scale 2, no copy-free top.
SEL = dict(fwd=11, inv=71, leaf=0, bottom=23, top=0, ident=2, scale=2, fwd4=104)


def sha(data):
    return hashlib.sha256(data if isinstance(data, bytes) else data.encode()).hexdigest()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--source', default='final_main.cpp')
    ap.add_argument('--mode', type=int, default=None, help='QL_MODE (solve_main.cpp only)')
    ap.add_argument('--probe', action='store_true', help='define QPOLY_PROBE (stderr phase line)')
    ap.add_argument('--define', action='append', default=[])
    ap.add_argument('--out', default=str(root / 'work/ntt/yosupo_convolution_mod_large.cpp'))
    args = ap.parse_args()
    main_src = (here / args.source).read_text()
    io = (here / 'io007.hpp').read_text().replace('#pragma once\n', '')
    io_sse = (here / 'io007_sse.hpp').read_text().replace('#pragma once\n', '')
    core = (here / 'large_core.hpp').read_text().replace('#pragma once\n', '')
    large = (here / 'large.hpp').read_text().replace('#pragma once\n', '')
    kernel = (here.parent / 'asm_explore/kernels/qasm.hpp').read_text().replace('#pragma once\n', '')
    asm = mya.trimmed(SEL['fwd'], SEL['inv'], SEL['leaf'], SEL['bottom'], SEL['top'], SEL['ident'], SEL['scale'], SEL['fwd4'])
    inc = '#include "asm_bfly.inc"\n#include "asm_leaf.inc"\n#include "asm_bottom.inc"\n'
    assert kernel.count(inc) == 1
    kernel = kernel.replace(inc, asm)
    assert core.count('#include "../asm_explore/kernels/qasm.hpp"\n') == 1
    core = core.replace('#include "../asm_explore/kernels/qasm.hpp"\n', kernel)
    if '#include "large.hpp"\n' in main_src:   # experiment program: large.hpp includes the core
        large = large.replace('#include "large_core.hpp"\n', core)
        parts = (('io007.hpp', io), ('large.hpp', large))
    elif '#include "io007_sse.hpp"\n' in main_src:   # final_main_sse.cpp (406478's SSE I/O)
        parts = (('io007_sse.hpp', io_sse), ('large_core.hpp', core))
    else:
        parts = (('io007.hpp', io), ('large_core.hpp', core))
    for name, body in parts:
        line = f'#include "{name}"\n'
        assert main_src.count(line) == 1, name
        main_src = main_src.replace(line, body)
    assert '#include "' not in main_src
    defines = ([f'#define QL_MODE {args.mode}'] if args.mode is not None else []) + \
              (['#define QPOLY_PROBE'] if args.probe else []) + [f'#define {d.replace("=", " ", 1)}' for d in args.define]
    header = (
        '// Library Checker convolution_mod_large (https://judge.yosupo.jp/problem/convolution_mod_large).\n'
        '// Generated by work/ntt/conv_large/make_submission.py (QPoly exploration 010) from\n'
        f'//   conv_large/{args.source}  SHA256 {sha((here / args.source).read_bytes())[:16]}...\n'
        f'//   conv_large/large_core.hpp  SHA256 {sha((here / "large_core.hpp").read_bytes())[:16]}...  (exploration 010 driver)\n'
        f'//   conv_large/io007.hpp       SHA256 {sha((here / "io007.hpp").read_bytes())[:16]}...  (exploration 007 I/O, verbatim)\n'
        f'//   asm_explore/kernels/qasm.hpp SHA256 {sha((here.parent / "asm_explore/kernels/qasm.hpp").read_bytes())[:16]}...  (exploration 009 kernel)\n'
        f'// with generated assembly variants {SEL} (asm_explore/gen_asm.py output, trimmed).\n'
        '// Transform: cyclic convolution of length 2^lg >= N+M-1 modulo 998244353, split down to\n'
        '// x^8 - w leaves (roots of order <= 2^22 suffice for 2^25); lengths <= 2^22 use the\n'
        '// exploration-009 kernel unchanged, larger lengths the exploration-010 driver (large_core.hpp).\n'
        + '\n'.join(defines) + '\n')
    src = header + main_src
    Path(args.out).write_text(src)
    out = Path(args.out)
    print(out.relative_to(root) if out.is_relative_to(root) else out, len(src), 'bytes, SHA256', sha(src))


if __name__ == '__main__':
    main()
