#!/usr/bin/env python3
"""Copy each implementation's code, verbatim, out of its pinned source file.

usage: extract.py OUT_DIR

Writes OUT_DIR/{kactl,simd_v0,qgq_393435,ours_406478}.inc. Each source is pinned by
SHA256; the script fails if a source changed or a marker is missing. Nothing is edited
except that simd-v0 (global names in kactl_bench.cpp) is wrapped in `namespace simd0`.
"""
import hashlib
import sys
from pathlib import Path

here = Path(__file__).resolve().parent
root = here.parents[2]

SOURCES = {
    # the user's original benchmark: simd-v0 and KACTL
    'kactl_bench': (root / 'kactl_bench.cpp',
                    'c604a57aaa97fb30257eb9098695670abd0d1c0bcf527f78d0e60ce7e400bc7f'),
    # QgQ, https://judge.yosupo.jp/submission/393435 (fetched 2026-09-27 from
    # https://v3.api.judge.yosupo.jp/submissions/393435, field "source")
    '393435': (here / 'vendor/submission_393435.cpp',
               '79ae944ff15f4566678359a81596c47b016dc05978975f2e81d944e7897f1f12'),
    # our submission 406478 = this file without its two QPOLY_TIMING lines
    '406478': (root / 'work/ntt/yosupo_convolution_asm_shoup_io_sse.cpp',
               'c8d2d7ed1c2aa86d1ee53d46c9f880ffc4799d5ea33745d4979e3ead6268736c'),
}


def read(key):
    path, digest = SOURCES[key]
    data = path.read_bytes()
    got = hashlib.sha256(data).hexdigest()
    if got != digest:
        sys.exit(f'{path}: SHA256 {got}, expected {digest}')
    return data.decode()


def cut(text, begin, end, include_end=True):
    """text from the first `begin` to the next `end` (inclusive or not)."""
    i = text.index(begin)
    j = text.index(end, i)
    return text[i:j + len(end) if include_end else j]


def main():
    out = Path(sys.argv[1])
    out.mkdir(parents=True, exist_ok=True)
    kb, qgq, ours = read('kactl_bench'), read('393435'), read('406478')
    header = '// Generated by work/ntt/lc_bench/extract.py from {} (verbatim). Do not edit.\n'
    pieces = {
        'kactl': ('kactl_bench.cpp',
                  cut(kb, 'namespace KACTL {', '\n// Helper to access v8i array', False).rstrip() + '\n'),
        'simd_v0': ('kactl_bench.cpp',
                    'namespace simd0 {\n'
                    + cut(kb, 'using u32 = uint32_t;',
                          '// ============================================================================\n'
                          '// KACTL NTT for correctness testing', False)
                    + '}  // namespace simd0\n'),
        # ntt998.hpp region: pragmas, modint998, namespace eez::ntt998 (fast I/O and main() dropped)
        'qgq_393435': ('vendor/submission_393435.cpp',
                       cut(qgq, '#line 2 "ntt998.hpp"', '#undef EEZ_NTT998_RESTRICT') + '\n'),
        # pragmas, includes and namespace qasm (fast I/O, arena and main() dropped)
        'ours_406478': ('work/ntt/yosupo_convolution_asm_shoup_io_sse.cpp',
                        cut(ours, '#if defined(__GNUC__) && !defined(__clang__)', '}  // namespace qasm') + '\n'),
    }
    # The wrappers call exactly what each submission's main() calls.
    assert 'convolution_adaptive_mixed_normal_inplace(a.data(),b.data(),transform_size)' in qgq
    assert 'convert_to_montgomery(b.data(),' in qgq
    assert ('qasm::Kernel<qasm::Cfg<2, false, true, 0, false, 256, true, true, true, 1, true, true, '
            '11, 71, 0, 4, 23, 0, 2, 2, 104>>::run(') in ours
    for name, (src, body) in pieces.items():
        (out / f'{name}.inc').write_text(header.format(src) + body)
    print(f'extracted {len(pieces)} implementations into {out}')


if __name__ == '__main__':
    main()
