#!/usr/bin/env python3
"""Single-file Library Checker convolution_mod_large submission from an exploration-011 program.

Recursively inlines local includes (`#include "path"`, relative to the including file, each file
once, `#pragma once` dropped). The exploration-009 kernel's assembly includes are replaced by the
selected generated variants only (asm_explore/make_yosupo_asm.py's trimmed(), the selection in
conv_large/make_submission.py). Macros are prepended as #define lines.

usage: make_submission.py [--source io_main.cpp] [--define NAME=VALUE ...] [--probe] [--out PATH]
"""
import argparse
import hashlib
import importlib.util
import re
import sys
from pathlib import Path

sys.dont_write_bytecode = True
here = Path(__file__).resolve().parent
root = here.parents[2]
spec = importlib.util.spec_from_file_location('cls', here.parent / 'conv_large/make_submission.py')
cls = importlib.util.module_from_spec(spec)
spec.loader.exec_module(cls)   # provides SEL and the asm_explore trimmed() module (cls.mya)

ASM_INCLUDES = '#include "asm_bfly.inc"\n#include "asm_leaf.inc"\n#include "asm_bottom.inc"\n'
INCLUDE = re.compile(r'^#include "([^"]+)"\n', re.M)


def sha(data):
    return hashlib.sha256(data if isinstance(data, bytes) else data.encode()).hexdigest()


def inline(path, seen, used):
    path = path.resolve()
    if path in seen:
        return ''
    seen.add(path)
    used.append(path)
    text = path.read_text().replace('#pragma once\n', '')
    if path.name == 'qasm.hpp':
        s = cls.SEL
        assert text.count(ASM_INCLUDES) == 1
        text = text.replace(ASM_INCLUDES, cls.mya.trimmed(s['fwd'], s['inv'], s['leaf'], s['bottom'], s['top'],
                                                          s['ident'], s['scale'], s['fwd4']))
    return INCLUDE.sub(lambda m: inline(path.parent / m.group(1), seen, used), text)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--source', default='io_main.cpp')
    ap.add_argument('--define', action='append', default=[])
    ap.add_argument('--probe', action='store_true')
    ap.add_argument('--out', default=str(root / 'work/ntt/yosupo_convolution_mod_large_io.cpp'))
    args = ap.parse_args()
    used = []
    body = inline(here / args.source, set(), used)
    assert '#include "' not in body
    defines = [f'#define {d.replace("=", " ", 1)}' for d in args.define] + (['#define QPOLY_PROBE'] if args.probe else [])
    header = ('// Library Checker convolution_mod_large (https://judge.yosupo.jp/problem/convolution_mod_large).\n'
              '// Generated by work/ntt/io_large/make_submission.py (QPoly exploration 011) from:\n'
              + ''.join(f'//   {p.relative_to(root / "work/ntt")}  SHA256 {sha(p.read_bytes())[:16]}...\n' for p in used)
              + f'// with generated assembly variants {cls.SEL} (asm_explore/gen_asm.py output, trimmed).\n'
              + ''.join(d + '\n' for d in defines))
    src = header + body
    out = Path(args.out)
    out.write_text(src)
    print(out.relative_to(root) if out.is_relative_to(root) else out, len(src), 'bytes, SHA256', sha(src))


if __name__ == '__main__':
    main()
