#!/usr/bin/env python3
"""Generate the Library Checker convolution_mod submission from the tested kernel.

Output: work/ntt/yosupo_convolution_shoup.cpp (single file, GCC, x86-64 AVX2).
The kernel text is kernels/flip.hpp verbatim; I/O is the fast_io namespace from
work/ntt/yosupo_convolution_asm_radix4_pair_large_fixed.cpp (exploration 006).
"""
import hashlib, re
from pathlib import Path

here = Path(__file__).resolve().parent
root = here.parents[2]
kernel = (here / 'kernels/flip.hpp').read_text()
kernel = kernel.replace('#pragma once\n', '')
kernel = re.sub(r'#include <[a-z_]+(\.h)?>\n', '', kernel)
wrapper = (root / 'work/ntt/yosupo_convolution_asm_radix4_pair_large_fixed.cpp').read_text()
io = wrapper[wrapper.index('namespace fast_io {'):wrapper.index('} // namespace fast_io') + len('} // namespace fast_io')]
khash = hashlib.sha256((here / 'kernels/flip.hpp').read_bytes()).hexdigest()

CONFIG = 'qflip::Cfg<2, false, true, 0, false, 256, true, true, true, 1, true>'  # s_ns_olb

src = f'''// Library Checker convolution_mod (https://judge.yosupo.jp/problem/convolution_mod).
// Generated by work/ntt/uop_explore/make_yosupo.py; kernel = kernels/flip.hpp
// (SHA256 {khash}) with config s_ns_olb:
//   Shoup twiddle multiplication, block-layout root tables, opaque-product barrier,
//   unaligned odd-lane loads, 256-vector tiles, fused h=1 stage + direct8 leaves.
// Target: judge GCC 15.2, g++ -O2 -std=c++23 -march=native, AMD EPYC 7B13 (Zen 3).
// Input/output: canonical residues mod 998244353, 1 <= N, M <= 2^19. Zero upper
// halves make the forward top radix-2 layer a copy. Arrays are padded because the
// unaligned odd-lane loads read 4 bytes past the last vector.
// Prints the transform time to stderr (compute_ms=...) unless QPOLY_QUIET is defined.
#if defined(__GNUC__) && !defined(__clang__)
#pragma GCC optimize("O3,unroll-loops")
#endif
#pragma GCC target("avx2,bmi")
#include <immintrin.h>
#include <algorithm>
#include <cassert>
#include <chrono>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <type_traits>
#include <vector>
#include <sys/mman.h>
#include <sys/stat.h>
#include <unistd.h>
{kernel}
{io}

// One judge case per process. BSS supplies the zero padding without an input copy.
constexpr int max_transform = 1 << 20;
alignas(64) static uint32_t a[max_transform + 16], b[max_transform + 16];
alignas(64) static uint32_t roots[max_transform / 8 + 16], inverse_roots[max_transform / 8 + 16];

int main() {{
    fast_io::Input in;
    const unsigned n = in.read(), m = in.read();
    if (n == 0 || m == 0 || n > (1u << 19) || m > (1u << 19)) return 1;
    for (unsigned i = 0; i < n; ++i) a[i] = in.read();
    for (unsigned i = 0; i < m; ++i) b[i] = in.read();
    const unsigned count = n + m - 1;
    int length = 64;  // kernel minimum
    while (unsigned(length) < count) length *= 2;
    int root_size = 0;
    auto t0 = std::chrono::steady_clock::now();
    {CONFIG.replace('qflip::Cfg', 'qflip::Kernel<qflip::Cfg')}>::run(length, a, b, roots, inverse_roots, root_size, true, int(n), int(m));
    auto t1 = std::chrono::steady_clock::now();
    static fast_io::Output out;
    for (unsigned i = 0; i < count; ++i) out.write(a[i], i + 1 == count ? '\\n' : ' ');
    out.flush();
#ifndef QPOLY_QUIET
    std::fprintf(stderr, "compute_ms=%.4f\\n", std::chrono::duration<double, std::milli>(t1 - t0).count());
#endif
    return std::fflush(stdout) == 0 ? 0 : 1;
}}
'''
out = root / 'work/ntt/yosupo_convolution_shoup.cpp'
out.write_text(src)
print(out, hashlib.sha256(src.encode()).hexdigest())
