#!/usr/bin/env python3
"""Generate Library Checker convolution_mod submissions from the tested kernel.

Deliverable: work/ntt/yosupo_convolution_shoup.cpp (SSE I/O from exploration 007).
Experiment variant: work/ntt/uop_explore/generated/yosupo_shoup_basicio.cpp (I/O
from exploration 006). The kernel text is kernels/flip.hpp verbatim.
"""
import hashlib, re
from pathlib import Path

here = Path(__file__).resolve().parent
root = here.parents[2]
kernel = (here / 'kernels/flip.hpp').read_text()
kernel = kernel.replace('#pragma once\n', '')
kernel = re.sub(r'#include <[a-z_]+(\.h)?>\n', '', kernel)
khash = hashlib.sha256((here / 'kernels/flip.hpp').read_bytes()).hexdigest()
CONFIG = 'qflip::Cfg<2, false, true, 0, false, 256, true, true, true, 1, true, true>'  # s_ns_olbp

basic_src = (root / 'work/ntt/yosupo_convolution_asm_radix4_pair_large_fixed.cpp').read_text()
basic_io = basic_src[basic_src.index('namespace fast_io {'):basic_src.index('} // namespace fast_io') + len('} // namespace fast_io')]
sse_path = root / 'work/ntt/yosupo_convolution_asm_radix4_pair_large_fixed_io_sse.cpp'
sse_src = sse_path.read_text()
sse_io = sse_src[sse_src.index("// Selected uint32 I/O from QgQ's submission 393435"):sse_src.index('constexpr int max_transform')]

IO = {
    'basic': dict(text=basic_io, note='I/O: fast_io from work/ntt/yosupo_convolution_asm_radix4_pair_large_fixed.cpp (exploration 006).',
                  read='in.read()', setup='    fast_io::Input in;\n',
                  write='''    static fast_io::Output out;
    for (unsigned i = 0; i < count; ++i) out.write(a[i], i + 1 == count ? '\\n' : ' ');
    out.flush();
''', ret='std::fflush(stdout) == 0 ? 0 : 1'),
    'sse': dict(text=sse_io, note=('I/O: sse_short_lut8 from work/ntt/yosupo_convolution_asm_radix4_pair_large_fixed_io_sse.cpp\n'
                                    '// (exploration 007), adapted from QgQ, https://judge.yosupo.jp/submission/393435\n'
                                    '// (2026-08-14); no license notice was present in the displayed source.'),
                read='read_sse_short(input_cursor)', setup='''    fastio_unsafe_impl::input in;
    static fastio_unsafe_impl::output out;
    char* input_cursor = in.cursor();
    char* output_cursor = out.begin();
    char* const output_end = out.end();
''', write='''    for (unsigned i = 0; i < count; ++i) write_mod998(out, output_cursor, output_end, a[i]);
    out.finish(output_cursor);
''', ret='0'),
}

def generate(io):
    d = IO[io]
    return f'''// Library Checker convolution_mod (https://judge.yosupo.jp/problem/convolution_mod).
// Generated by work/ntt/uop_explore/make_yosupo.py; kernel = kernels/flip.hpp
// (SHA256 {khash}) with config s_ns_olbp:
//   Shoup twiddle multiplication, block-layout root tables, opaque-product barrier,
//   unaligned odd-lane loads, 256-vector tiles, fused h=1 stage + direct8 leaves
// whose windows are built one batch ahead of their multiply-accumulate.
// Target: judge GCC 15.2, g++ -O2 -std=c++23 -march=native, AMD EPYC 7B13 (Zen 3).
// Input/output: canonical residues mod 998244353, 1 <= N, M <= 2^19. Zero upper
// halves make the forward top radix-2 layer a copy.
// Memory: one 2 MiB-aligned anonymous mapping (A, B, both root tables) with a
// transparent-huge-page hint, pre-faulted before the timed transform (the record
// holder likewise pre-faults its arrays before its timer). Arrays have 16 words of
// padding because the unaligned odd-lane loads read 4 bytes past the last vector.
// Prints the transform time to stderr (compute_ms=...) unless QPOLY_QUIET is defined.
// {d['note']}
#if defined(__GNUC__) && !defined(__clang__)
#pragma GCC optimize("O3,unroll-loops")
#endif
#pragma GCC target("avx2,bmi")
#include <immintrin.h>
#include <algorithm>
#include <array>
#include <cassert>
#include <cerrno>
#include <chrono>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <type_traits>
#include <vector>
#include <sys/mman.h>
#include <sys/stat.h>
#include <unistd.h>
{kernel}
{d['text']}

// Pre-faulted 2 MiB-aligned zeroed words (huge pages when the kernel allows them).
static uint32_t* arena(size_t words) {{
    constexpr size_t huge = size_t(2) << 20;
    const size_t bytes = (words * 4 + huge - 1) & ~(huge - 1);
    char* raw = static_cast<char*>(mmap(nullptr, bytes + huge, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0));
    if (raw == MAP_FAILED) std::exit(1);
    char* p = reinterpret_cast<char*>((reinterpret_cast<uintptr_t>(raw) + huge - 1) & ~uintptr_t(huge - 1));
#if defined(MADV_HUGEPAGE) && !defined(QPOLY_NO_HUGEPAGE)
    madvise(p, bytes, MADV_HUGEPAGE);
#endif
    bool populated = false;
#ifdef MADV_POPULATE_WRITE
    populated = madvise(p, bytes, MADV_POPULATE_WRITE) == 0;
#endif
    if (!populated) for (size_t i = 0; i < bytes; i += 4096) static_cast<volatile char*>(p)[i] = 0;
    return reinterpret_cast<uint32_t*>(p);
}}

int main() {{
{d['setup']}    const unsigned n = {d['read']}, m = {d['read']};
    if (n == 0 || m == 0 || n > (1u << 19) || m > (1u << 19)) return 1;
    const unsigned count = n + m - 1;
    int length = 64;  // kernel minimum
    while (unsigned(length) < count) length *= 2;
    const size_t pad = 16, len = size_t(length) + pad, tab = size_t(length) / 8 + pad;
    uint32_t* const a = arena(2 * len + 2 * tab);
    uint32_t *const b = a + len, *const roots = b + len, *const inverse_roots = roots + tab;
    for (unsigned i = 0; i < n; ++i) a[i] = {d['read']};
    for (unsigned i = 0; i < m; ++i) b[i] = {d['read']};
    int root_size = 0;
    auto t0 = std::chrono::steady_clock::now();
    {CONFIG.replace('qflip::Cfg', 'qflip::Kernel<qflip::Cfg')}>::run(length, a, b, roots, inverse_roots, root_size, true, int(n), int(m));
    auto t1 = std::chrono::steady_clock::now();
{d['write']}#ifndef QPOLY_QUIET
    std::fprintf(stderr, "compute_ms=%.4f\\n", std::chrono::duration<double, std::milli>(t1 - t0).count());
#endif
    return {d['ret']};
}}
'''

outs = {'sse': root / 'work/ntt/yosupo_convolution_shoup.cpp',
        'basic': here / 'generated/yosupo_shoup_basicio.cpp'}
for io, path in outs.items():
    path.parent.mkdir(parents=True, exist_ok=True)
    src = generate(io)
    path.write_text(src)
    print(path.relative_to(root), hashlib.sha256(src.encode()).hexdigest())
