#!/usr/bin/env python3
"""Generate focused I/O ablations; the frozen NTT is never transformed."""
from pathlib import Path
import hashlib
import json

root = Path(__file__).resolve().parents[3]
here = Path(__file__).resolve().parent
out = root / 'build/io_explore'
out.mkdir(parents=True, exist_ok=True)
baseline = root / 'work/ntt/yosupo_convolution_asm_radix4_pair_large_fixed_io393435.cpp'
source = baseline.read_text()
assert hashlib.sha256(baseline.read_bytes()).hexdigest() == '1b55ca7f3edf44e8e18b9f62503f5bbb3ec2595267dcf52a302b8a0d966a5899'
start = source.index('// Selected uint32 I/O')
end = source.index('constexpr int max_transform =')
io = source[start:end]
extra = (here / 'alternatives.inc').read_text()
variants = {
    'baseline': ('base', 'base', False),
    'lut8': ('base', 'base', True),
    'swar': ('swar', 'base', False),
    'sse': ('sse', 'base', False),
    'split': ('base', 'split', False),
    'two_digits': ('base', 'two_digits', False),
    'lut8_split': ('base', 'split', True),
    'swar_split': ('swar', 'split', False),
    'swar_two_digits': ('swar', 'two_digits', False),
}
includes = '''#include <array>
#include <cerrno>
#include <immintrin.h>
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <vector>
#include <sys/mman.h>
#include <sys/stat.h>
#include <unistd.h>
'''
bench = includes
bench += '''#if defined(__GNUC__) && !defined(__clang__)
#pragma GCC optimize("O3,unroll-loops")
#pragma GCC target("avx2,bmi")
#endif
'''
for name, (reader, writer, lut8) in variants.items():
    body = io.replace('std::array<uint32_t, 1 << 14>', 'std::array<uint8_t, 1 << 14>') if lut8 else io
    read = 'read_mod998_u32' if reader == 'base' else 'read_' + reader
    write = 'write_mod998' if writer == 'base' else 'write_' + writer
    # The helpers use the unmodified reader/writer for shorter-number fallback.
    body += extra
    main = source[end:].replace('read_mod998_u32(', read+'(').replace('write_mod998(', write+'(')
    candidate = f'// I/O experiment: {name}. Generated by work/ntt/io_explore/generate.py.\n'
    candidate += source[:start] + body + main
    (out / (name+'.cpp')).write_text(candidate)
    bench += f'namespace io_{name} {{\n' + body + f'''
__attribute__((noinline)) void read_array(char* p, uint32_t* dst, size_t n) {{
    for (size_t i=0;i<n;++i) dst[i]={read}(p);
}}
__attribute__((noinline)) size_t write_array(const uint32_t* src, size_t n, char* dst, size_t capacity) {{
    static fastio_unsafe_impl::output sink;
    char* p=dst;
    for (size_t i=0;i<n;++i) {write}(sink,p,dst+capacity,src[i]);
    return size_t(p-dst);
}}
}} // namespace io_{name}
'''
bench += '''struct IOEntry {
const char* name;
void (*read)(char*,uint32_t*,size_t);
size_t (*write)(const uint32_t*,size_t,char*,size_t);
};
const IOEntry entries[]={
'''
bench += ''.join(f'{{"{name}",io_{name}::read_array,io_{name}::write_array}},\n' for name in variants)
bench += '};\n'
(out/'generated.hpp').write_text(bench)
(out/'manifest.json').write_text(json.dumps({name: hashlib.sha256((out/(name+'.cpp')).read_bytes()).hexdigest() for name in variants}, indent=2)+'\n')
print((out/'manifest.json').read_text())
